export const OPEN_MODAL = 'modal/OPEN_MODAL';
export const CLOSE_MODAL = 'modal/CLOSE_MODAL';

export const MODAL_UNLOADED = 'MODAL_UNLOADED';

export const CHANGE_ACTIVE_ITEM = 'CHANGE_ACTIVE_ITEM';

export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

export const REQUEST_INDIVIDUAL_POST = 'REQUEST_INDIVIDUAL_POST';
export const RECEIVE_INDIVIDUAL_POST = 'RECEIVE_INDIVIDUAL_POST';

export const ADD_COMMENT = 'ADD_COMMENT';

export const POST_UPVOTED = 'POST_UPVOTED';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';

export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';

export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';

export const PROFILE_PAGE_LOADED = 'PROFILE_PAGE_LOADED';
export const PROFILE_PAGE_UNLOADED = 'PROFILE_PAGE_UNLOADED';

export const PROFILE_SUBTYPE_LOADED = 'PROFILE_SUBTYPE_LOADED';
