export const OPEN_MODAL = 'modal/OPEN_MODAL';
export const CLOSE_MODAL = 'modal/CLOSE_MODAL';

export const CHANGE_ACTIVE_ITEM = 'CHANGE_ACTIVE_ITEM';

// export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'
export const REQUEST_POSTS = 'REQUEST_POSTS';

export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

// export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
